name: Commit Updated cdk.json
on: 
  workflow_call:
    inputs:
      environment:
        description: "CDK environment key, which contains the config in the cdk.json"
        type: string
        required: true
    secrets:
      repo-write-token:
        description: "GitHub PAT with write permissions to the repo"
        required: true
jobs:
  update-cdk-image-tag-for-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.repo-write-token }}
      - name: Download cdk.json
        uses: actions/download-artifact@v3
        with:

          name: context
      - name: Diff cdk.json
        id: filter
        run: |
          git diff HEAD --quiet || echo "new-context=true" >> $GITHUB_OUTPUT 
      - name: Commit and push
        if: steps.filter.outputs.new-context == 'true'
        env:
          CDK_ENV: ${{ inputs.environment }}
          BRANCH: ${{ github.ref_name }}
        run: |
          git config user.email "deploy@aps.org"
          git config user.name "Deploy Bot"
          git checkout $BRANCH
          git add cdk.json
          git commit -m "Updated config for $CDK_ENV deployment"
          git push
          

