on:
  workflow_call:
    inputs:
      matrix:
        type: string

jobs:
  dynamic-matrix:
    strategy:
      matrix:  ${{ fromJSON({\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}) }}
    runs-on: ubuntu-latest
    # env:
    #   value: ${{ fromJSON(inputs.matrix) }}
    steps: 
      - run: echo $value