on:
  workflow_call:
    inputs:
      matrix:
        type: string

jobs:
  dynamic-matrix:
    strategy:
      matrix:  ${{ fromJSON(inputs.matrix) }}
    runs-on: ubuntu-latest
    steps: 
      - run: echo $value
        env:
          value: ${{ matrix.project }}