on:
  workflow_call:
    inputs:
      matrix:
        type: string

jobs:
  dynamic-matrix:
    # strategy:
    #   matrix: ${{ fromJson(inputs.matrix) }}
    runs-on: ubuntu-latest
    env:
      value: ${{ inputs.matrix }}
    steps: 
      - run: echo $value