on:
  workflow_call:
    inputs:
      environment:
        description: "CDK environment that this will deploy to"
        required: true
        type: string
      region: 
        description: "AWS Region that this CDK Stack should deploy to"
        type: string
        default: us-east-1
jobs:
  reusable-cicd-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: 
        node-version: "18"
    - name: Install
      run: npm ci
    - name: Linting
      run: npm run lint
    - name: Unit Tests
      run: npm run test:unit
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_CDK_DEPLOY_ROLE }}
        aws-region: ${{ inputs.region }}
    - name: Synth
      env:
        CDK_ENV: ${{ inputs.environment }}
      run: npm cdk synth --context env=$CDK_ENV
    - name: Deploy
      run: npm cdk deploy --require-approval=never
