on:
  push:
    branches:
      - main
jobs:
  ecr-build-and-deploy: 
    uses: ./.github/workflows/_reusable-ecr-build-and-push.yaml
    permissions:
      id-token: write
      contents: read
    with:
      ecr-repo-name: test-cicd-lambda
      app-path: ./lambdas/hello-world
      environment: prod
    secrets:
      AWS_ECR_ROLE: ${{ secrets.AWS_ECR_ROLE }}
  update-cdk-context:
    needs: ecr-build-and-deploy
    uses: ./.github/workflows/_reusable-update-cdk-image-tag.yaml
    with:
      environment: prod
      image-tag-key: lambda
      updated-tag: ${{ needs.ecr-build-and-deploy.outputs.updated-tag }}
    secrets:
      repo-write-token: ${{ secrets.GH_WRITE_TOKEN }}
  call-cicd:
    needs: update-cdk-context
    uses: ./.github/workflows/_reusable-cicd-template.yaml
    permissions:
      id-token: write
      contents: read
    with:
      ecr-repo-name: test-cicd-lambda
      environment: prod
    secrets:
      AWS_CDK_DEPLOY_ROLE: ${{ secrets.AWS_CDK_DEPLOY_ROLE }}
