on:
  push:
    branches:
      - main
jobs:
  ecr-build-and-deploy: 
    uses: ./.github/workflows/_reusable-ecr-build-and-push.yaml
    permissions:
      id-token: write
      contents: read
    with:
      ecr-repo-name: test-cicd-repo
      app-path: ./lambdas/hello-world
      environment: prod
  call-cicd:
    needs: ecr-build-and-deploy
    uses: ./.github/workflows/_reusable-cicd-template.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
