on:
  push:
    branches:
      - ci/dynamic-matrix

jobs:
  dynamic-matrix:
    uses: ./.github/workflows/_dynamic-matrix.yaml
    with:
      matrix: ${{ jq -r . ./.github/workflows/projects.json }}