on:
  push:
    branches:
      - ci/dynamic-matrix

jobs:
  dynamic-matrix:
    uses: ./.github/workflows/_dynamic-matrix.yaml
    with:
      matrix: '{"parameters":[{"project":"foo","config":"Debug"},{"project":"bar","config":"Release"}]}'