on:
  push:
    branches:
      - development
jobs:
  uploads:
    uses: ./.github/workflows/upload.yaml
    strategy:
      matrix:
        text:
          - A
          - B
          - C
  download:
    runs-on: ubuntu-latest
    needs: uploads
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: artifact
      - run: cat artifact.txt

