on: 
  workflow_call:
    inputs:
      text: 
        type: string
jobs: 
  upload:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: echo $TEXT >> artifact.txt
        env:
          TEXT: ${{ inputs.text }}
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact.txt